### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Lin-Yux** [BradhamLab/icat#26]
Hi @dakota-hawkins:
  Thanks for developing this useful package, but when I tried to install icat, some errors ouccured: 
  `pip install icat-sc`

  `ERROR: Cannot install icat-sc==0.1.2 and icat-sc==0.1.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    icat-sc 0.1.3 depends on sslouvain
    icat-sc 0.1.2 depends on sslouvain

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies`

How could I solve it ? looking forward to your reply.
Lin-Yux

**Comment by dakota-hawkins** [comment]
Hi Lin-Yux!

Thanks for trying out the package, and letting us know about the install error. I'll take a look at it tomorrow and let you know what fixes I come up with.

All the best!

Dakota

**Comment by dakota-hawkins** [comment]
Hi Lin-Yux!

The issue is that the sslouvain package (found [here](https://github.com/BradhamLab/sslouvain)) is not currently on PyPI. The package relies on a custom C extension, that I've been having some issue with in terms of building a `.whl` that fits a format accepted by PyPI. 

On my linux machine, I have been able to install the package using the set of commands:

```bash
pip install louvain  # sslouvain is built from this package, this will ensure the necessary sslouvain dependencies are installed
git clone https://github.com/BradhamLab/sslouvain
cd sslouvain
python setup.py build
python setup.py install
pip install icat-sc
```

Obviously this is just a work around while I work on getting a functional `.whl` of `sslouvain` up on PyPI, so I'll leave this issue open until the entire package can be installed entirely via `pip`.

Please feel free to reach out if you have any other questions about the package including use / documentation, etc. 


Best,

Dakota

**Comment by Lin-Yux** [comment]
Hi @dakota-hawkins:
  I'm appreciate to receive your timely advice. I tried to clone BradhamLab/sslouvain and installed it on my machine, however, it still caused some error:

```
  (PyG) lyx@:~/icat/sslouvain$ python setup.py build

running build
running build_py
UPDATING build/lib.linux-x86_64-cpython-39/sslouvain/_version.py
set build/lib.linux-x86_64-cpython-39/sslouvain/_version.py to 'v0.1.1+6.gbeac73a'
running build_ext
Cannot find the C core of igraph on this system using pkg-config.
We will now try to download and compile the C core from scratch.
Version number of the C core: 0.1.1

Version 0.1.1 of the C core of igraph is not found among the nightly builds.
Use the --c-core-version switch to try a different version.

Could not download and compile the C core of igraph.

WARNING: we were not able to detect where igraph is installed on
your machine (if it is installed at all). We will use the fallback
library and include paths hardcoded in setup.py and hope that the
C core of igraph is installed there.

If the compilation fails and you are sure that igraph is installed
on your machine, adjust the following two variables in setup.py
accordingly and try again:

- LIBIGRAPH_FALLBACK_INCLUDE_DIRS ['/usr/include/igraph', '/usr/local/include/igraph']
- LIBIGRAPH_FALLBACK_LIBRARY_DIRS []

Build type: dynamic extension                                    
Include path: /usr/include/igraph /usr/local/include/igraph
Library path: 
Linked dynamic libraries: igraph
Linked static libraries: 
Extra compiler options: 
Extra linker options: 
building 'sslouvain._c_louvain' extension
gcc -pthread -B /home/lyx/miniconda3/envs/PyG/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/lyx/miniconda3/envs/PyG/include -fPIC -O2 -isystem /home/lyx/miniconda3/envs/PyG/include -fPIC -Iinclude -I/usr/include/igraph -I/usr/local/include/igraph -I/home/lyx/miniconda3/envs/PyG/include/python3.9 -c src/CPMVertexPartition.cpp -o build/temp.linux-x86_64-cpython-39/src/CPMVertexPartition.o
In file included from include/MutableVertexPartition.h:5:0,
                 from include/ResolutionParameterVertexPartition.h:4,
                 from include/LinearResolutionParameterVertexPartition.h:4,
                 from include/CPMVertexPartition.h:4,
                 from src/CPMVertexPartition.cpp:1:
include/GraphHelper.h:4:20: fatal error: igraph.h: not files or dirs
compilation terminated.
```

I found that LIBIGRAPH_FALLBACK_INCLUDE_DIRS was not the path to my miniconda-env, so i changed these codes in setup.py,  however, it still failed: 

```
src/MutableVertexPartition.cpp: In constructor ‘MutableVertexPartition::MutableVertexPartition(Graph*, const std::vector<long unsigned int>&, const std::vector<bool>&)’:
src/MutableVertexPartition.cpp:54:43: warning: delegating constructors only available with -std=c++11 or -std=gnu++11
   MutableVertexPartition(graph, membership) {
                                           ^
src/MutableVertexPartition.cpp: In member function ‘void MutableVertexPartition::set_mutable(const std::vector<bool>&)’:
src/MutableVertexPartition.cpp:177:16: error: ‘to_string’ is not a member of ‘std’
     msg.append(std::to_string(this -> graph -> vcount()));
                ^
src/MutableVertexPartition.cpp:179:16: error: ‘to_string’ is not a member of ‘std’
     msg.append(std::to_string(mutables.size()));
                ^
error: command '/usr/bin/gcc' failed with exit code 1
```

By the way, I just an user on Labs' HPC and do not have the root account. Could I get more your suggestions?

Best, 

Lin-Yux

**Comment by dakota-hawkins** [comment]
Hi Lin-Yux,

I just managed to generate a Linux `.whl` for the `sslouvain` package which was accepted by PyPI. `pip install icat-sc` should now work, and I've managed to get it to work from a fresh conda environment.

If you're not using Linux, I will probably need more time to figure out how to compile the package for different operating systems.

Let me know if the above works!

**Comment by Lin-Yux** [comment]
Hi dakota-hawkins!

Your suggestion does worked! For details, my python version is 3.9.13 and gcc version is 10.3.0 on linux. 
Finally, thanks u to develop such a wonderful package and guide me to tackle the problem.

All best
Lin-Yux
